[package]
name = "x-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
serde_json = "1.0.140"
tree-sitter-cli = "0.25.3"
tree-sitter-highlight = "0.25.3"
tree-sitter-loader = "0.25.3"

