on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      id-token: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # for vendored parsers
          submodules: 'true'

      - uses: DeterminateSystems/nix-installer-action@main
      # EOL
      # - uses: DeterminateSystems/magic-nix-cache-action@main

      # seperate build deps to get better log
      - name: Build x-rs
        run: nix build ./nix#x-rs

      - name: Build LaTeX bundled
        run: nix build ./nix#texUsed

      - name: Build forester
        run: nix build ./nix#forester

      - name: Build forest
        run: nix run ./nix#build

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: forest
          directory: output
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
